"""Code generation engine — produces ACME assembly from a ProjectSpec."""

from pathlib import Path
from typing import TYPE_CHECKING

from .config import get_output_src_dir, get_output_build_dir
from .spec_parser import _parse_int, note_to_sid_freq

if TYPE_CHECKING:
    from .spec_parser import ProjectSpec, Action


def _compute_init_addr(code_start: int) -> int:
    base = code_start + 8
    target = base + len(str(base))
    return target


def generate_assembly(spec: "ProjectSpec") -> str:
    lines: list[str] = []
    init_addr = _compute_init_addr(spec.memory.code_start)
    _emit_header(spec, lines)
    _emit_basic_header(spec, init_addr, lines)
    _emit_init(spec, init_addr, lines)
    _emit_irq_handler(spec, lines)

    if _has_behaviors(spec):
        _emit_behavior_variables(spec, lines)
        _emit_behavior_main_loop(spec, lines)
        _emit_sprite_init_behavior(spec, lines)
        _emit_behavior_frame(spec, lines)
        _emit_behavior_update_sprites(spec, lines)
        _emit_collision_handlers(spec, lines)
    else:
        _emit_variables(lines)
        _emit_main_loop(spec, lines)
        _emit_sprite_init(spec, lines)
        _emit_joystick_read(lines)
        _emit_sprite_update(spec, lines)

    _emit_user_routines(spec, lines)
    _emit_sprite_data(spec, lines)
    _emit_routines_footer(spec, lines)
    return "\n".join(lines)


def _has_behaviors(spec: "ProjectSpec") -> bool:
    return bool(spec.behaviors) and any(b.actions for b in spec.behaviors)


def _emit_header(spec: "ProjectSpec", lines: list[str]) -> None:
    lines.append(f";; Generated by c64devk v0.1.0")
    lines.append(f";; Project: {spec.name}")
    lines.append(f";; DO NOT EDIT — modify spec files instead")
    lines.append("")
    lines.append(f'!source "macros/c64devk.acme"')
    lines.append("")


def _emit_basic_header(spec: "ProjectSpec", init_addr: int, lines: list[str]) -> None:
    if not spec.basic:
        return
    code_start = spec.memory.code_start
    bas_digits = ", ".join(f"${ord(d):02x}" for d in str(init_addr))
    num_digits = len(str(init_addr))
    next_line = code_start + 6 + num_digits
    lines.append(f"* = ${code_start:04X}")
    lines.append("")
    lines.append(f"\t;; BASIC header: SYS {init_addr}")
    lines.append(f"\t!byte ${next_line & 0xFF:02X}, ${(next_line >> 8) & 0xFF:02X}, $0a, $00, $9e, {bas_digits}, $00")
    lines.append("\t!byte $00, $00")
    lines.append("")


def _emit_init(spec: "ProjectSpec", init_addr: int, lines: list[str]) -> None:
    lines.append(f"* = ${init_addr:04X}")
    lines.append("\tjmp init")
    lines.append("")
    lines.append("init:")
    lines.append("\tsei")
    lines.append("")
    _emit_screen_init(spec, lines)
    _emit_irq_setup(spec, lines)
    _emit_sprite_memory_setup(spec, lines)
    lines.append("")

    if _behaviors_need_text(spec):
        lines.append("\t;; Copy ROM charset to RAM for text display")
        lines.append("\tsei")
        lines.append("\tlda #$33")
        lines.append("\tsta $01")
        lines.append("\tldx #0")
        for page in range(8):
            src = 0xD000 + page * 0x100
            dst = spec.screen.charset_addr + page * 0x100
            lines.append(f"\tlda ${src:04X}, x")
            lines.append(f"\tsta ${dst:04X}, x")
        lines.append("\tinx")
        lines.append("\tbne *-16      ; continue copy loop")
        lines.append("\tlda #$37")
        lines.append("\tsta $01")
        lines.append("\tcli")
    else:
        lines.append("\tcli")
    lines.append("\tjsr init_sprites")
    lines.append("\tjmp main_loop")
    lines.append("")


def _emit_screen_init(spec: "ProjectSpec", lines: list[str]) -> None:
    sc = spec.screen
    lines.append("\t;; -- Screen setup --")
    lines.append(f"\tlda #${sc.background_color:02X}")
    lines.append("\tsta $d021")
    lines.append(f"\tlda #${sc.border_color:02X}")
    lines.append("\tsta $d020")

    vic_bank = (sc.screen_ram // 0x4000) % 4
    lines.append("\t;; Set VIC bank")
    lines.append("\tlda $dd00")
    lines.append("\tand #$fc")
    lines.append(f"\tora #${(~vic_bank) & 0x03:02X}")
    lines.append("\tsta $dd00")

    screen_vic_offset = (sc.screen_ram % 0x4000) // 0x400
    charset_vic_offset = (sc.charset_addr % 0x4000) // 0x400
    lines.append(f"\tlda #${((screen_vic_offset << 4) | charset_vic_offset):02X}")
    lines.append("\tsta $d018")

    mode_bits = 0
    if sc.mode == "multicolor":
        mode_bits |= 0x10
    if sc.multicolor:
        mode_bits |= 0x08
    lines.append("\tlda $d016")
    lines.append(f"\tora #${mode_bits:02X}")
    lines.append("\tsta $d016")
    lines.append("")


def _emit_irq_setup(spec: "ProjectSpec", lines: list[str]) -> None:
    lines.append("\t;; -- IRQ setup (raster) --")
    lines.append("\tlda #$7f")
    lines.append("\tsta $dc0d")
    lines.append("\tlda $dc0d")
    lines.append("")
    lines.append("\tlda #$01")
    lines.append("\tsta $d01a")
    lines.append("")
    lines.append("\tlda #<irq")
    lines.append("\tldx #>irq")
    lines.append("\tsta $0314")
    lines.append("\tstx $0315")
    lines.append("")
    lines.append("\tlda #$00")
    lines.append("\tsta $d012")
    lines.append("\tlda $d011")
    lines.append("\tand #$7f")
    lines.append("\tsta $d011")
    lines.append("")


def _emit_sprite_memory_setup(spec: "ProjectSpec", lines: list[str]) -> None:
    if not spec.sprites:
        return
    lines.append("\t;; -- Sprite memory setup --")
    sprite_ptr_base = spec.memory.sprite_data // 64
    screen_addr = spec.screen.screen_ram
    sprite_ptrs_base = screen_addr + 0x03F8
    for s in spec.sprites:
        ptr = sprite_ptr_base + s.index
        lines.append(f"\tlda #${ptr:02X}")
        lines.append(f"\tsta ${sprite_ptrs_base + s.index:04X}")
    lines.append("")


def _emit_irq_handler(spec: "ProjectSpec", lines: list[str]) -> None:
    lines.append("irq:")
    lines.append("\tlda $d019")
    lines.append("\tsta $d019")
    lines.append("\tinc frame_ready")
    lines.append("\tjmp $ea31")
    lines.append("")


def _emit_variables(lines: list[str]) -> None:
    lines.append("")
    lines.append("\t;; Variables — fixed at $0C00")
    lines.append("* = $0C00")
    lines.append("frame_ready:\t!byte 0")
    lines.append("joystick_state:\t!byte 0")
    lines.append("joystick_prev:\t!byte 0")
    lines.append("")


def _emit_main_loop(spec: "ProjectSpec", lines: list[str]) -> None:
    lines.append("main_loop:")
    lines.append("\t+c64_wait_frame")
    lines.append("")
    lines.append("\tjsr read_joystick")
    lines.append("\tjsr game_logic")
    lines.append("\tjsr update_sprites")
    lines.append("")
    lines.append("\tjmp main_loop")
    lines.append("")


def _emit_sprite_init(spec: "ProjectSpec", lines: list[str]) -> None:
    if not spec.sprites:
        lines.append("init_sprites:")
        lines.append("\trts")
        lines.append("")
        return

    lines.append("init_sprites:")
    for s in spec.sprites:
        ix_lo = 0xD000 + s.index * 2
        ix_hi = 0xD001 + s.index * 2
        lines.append(f"\t;; Sprite {s.index}: {s.name}")
        lines.append(f"\tlda #<{s.x}")
        lines.append(f"\tsta ${ix_lo:04X}")
        lines.append(f"\tlda #<{s.y}")
        lines.append(f"\tsta ${ix_hi:04X}")
        lines.append(f"\tlda #${s.color:02X}")
        lines.append(f"\tsta ${0xD027 + s.index:04X}")

        if s.x > 255:
            lines.append(f"\tlda $d010")
            lines.append(f"\tora #${1 << s.index:02X}")
            lines.append(f"\tsta $d010")

    lines.append("\t+c64_sprite_enable_all")
    lines.append("\trts")
    lines.append("")


def _emit_joystick_read(lines: list[str]) -> None:
    lines.append("read_joystick:")
    lines.append("\tlda joystick_state")
    lines.append("\tsta joystick_prev")
    lines.append("")
    lines.append("\tlda $dc00")
    lines.append("\teor #$ff")
    lines.append("\tsta joystick_state")
    lines.append("\trts")
    lines.append("")


def _emit_sprite_update(spec: "ProjectSpec", lines: list[str]) -> None:
    if not spec.sprites:
        lines.append("update_sprites:")
        lines.append("\trts")
        lines.append("")
        return

    lines.append("update_sprites:")
    first = spec.sprites[0]
    is_x = first.index * 2
    lines.append(f"\t;; Update {first.name} from joystick")
    lines.append("")
    lines.append("\t+c64_joy_check JOY_UP, .skip_up")
    lines.append(f"\tdec $d0{is_x+1:02X}")
    lines.append(".skip_up:")
    lines.append("")
    lines.append("\t+c64_joy_check JOY_DOWN, .skip_down")
    lines.append(f"\tinc $d0{is_x+1:02X}")
    lines.append(".skip_down:")
    lines.append("")
    lines.append("\t+c64_joy_check JOY_LEFT, .skip_left")
    lines.append(f"\tdec $d0{is_x:02X}")
    lines.append(".skip_left:")
    lines.append("")
    lines.append("\t+c64_joy_check JOY_RIGHT, .skip_right")
    lines.append(f"\tinc $d0{is_x:02X}")
    lines.append(".skip_right:")
    lines.append("")
    lines.append("\trts")
    lines.append("")


# ============================================================
# Behavior compiler — compiles behaviors.yaml actions to 6502
# ============================================================

def _behavior_action_counter() -> list[int]:
    return [0]


def _next_beh_label(counter: list[int], prefix: str = "b") -> str:
    counter[0] += 1
    return f".b_{prefix}_{counter[0]:x}"


def _sprite_index_for(spec: "ProjectSpec", name: str) -> int:
    for s in spec.sprites:
        if s.name == name:
            return s.index
    return -1


def _behaviors_need_joystick(spec: "ProjectSpec") -> bool:
    for b in spec.behaviors:
        for a in b.actions:
            if a.type == "read_joystick" or a.type == "update_sprite":
                return True
    return False


def _behaviors_need_score(spec: "ProjectSpec") -> bool:
    for b in spec.behaviors:
        for a in b.actions:
            if a.type == "inc_score":
                return True
    return False


def _behaviors_need_sound(spec: "ProjectSpec") -> bool:
    for b in spec.behaviors:
        for a in b.actions:
            if a.type == "play_sound":
                return True
    return False


def _behaviors_need_text(spec: "ProjectSpec") -> bool:
    for b in spec.behaviors:
        for a in b.actions:
            if a.type == "display_text":
                return True
    return False


def _behaviors_sound_voices(spec: "ProjectSpec") -> set[int]:
    voices: set[int] = set()
    for b in spec.behaviors:
        for a in b.actions:
            if a.type == "play_sound":
                voices.add(int(a.params.get("voice", 1)))
    return voices


def _emit_behavior_variables(spec: "ProjectSpec", lines: list[str]) -> None:
    lines.append("")
    lines.append("\t;; Variables — fixed at $0C00")
    lines.append("* = $0C00")
    lines.append("frame_ready:\t!byte 0")
    lines.append("joystick_state:\t!byte 0")
    lines.append("joystick_prev:\t!byte 0")
    if _behaviors_need_score(spec):
        lines.append("score:\t!byte 0, 0")
    if _behaviors_need_sound(spec):
        lines.append("sound_dur_1:\t!byte 0")
        lines.append("sound_dur_2:\t!byte 0")
        lines.append("sound_dur_3:\t!byte 0")
    lines.append("")


def _emit_behavior_main_loop(spec: "ProjectSpec", lines: list[str]) -> None:
    lines.append("main_loop:")
    lines.append("\t+c64_wait_frame")
    lines.append("")
    if _behaviors_need_joystick(spec):
        lines.append("\t;; Read joystick")
        lines.append("\tlda $dc00")
        lines.append("\teor #$ff")
        lines.append("\tsta joystick_state")
        lines.append("")

    lines.append("\tjsr behaviors_update")
    if _behaviors_need_sound(spec):
        lines.append("\tjsr sound_tick")
    lines.append("\tjsr update_sprites")
    lines.append("\tjsr game_logic")
    lines.append("")
    lines.append("\tjmp main_loop")
    lines.append("")


def _emit_behavior_frame(spec: "ProjectSpec", lines: list[str]) -> None:
    lines.append("behaviors_update:")
    cnt = _behavior_action_counter()

    for b in spec.behaviors:
        if b.type != "on_frame":
            continue
        lines.append(f"\t;; Behavior: {b.name}")
        for a in b.actions:
            _emit_action(spec, a, lines, cnt)
        lines.append("")

    _emit_collision_checks(spec, lines, cnt)

    if not any(b.type == "on_frame" for b in spec.behaviors):
        lines.append("\tnop")
    lines.append("\trts")
    lines.append("")

    if _behaviors_need_sound(spec):
        lines.append("sound_tick:")
        lines.append("\t+c64_sound_tick_all")
        lines.append("\trts")
        lines.append("")


def _emit_collision_checks(spec: "ProjectSpec", lines: list[str], cnt: list[int]) -> None:
    collision_behaviors = [b for b in spec.behaviors if b.type == "on_collision"]
    if not collision_behaviors:
        return

    grouped: dict[tuple[int, int], list] = {}
    for b in collision_behaviors:
        idx1 = _sprite_index_for(spec, b.collision_sprites[0]) if len(b.collision_sprites) >= 1 else -1
        idx2 = _sprite_index_for(spec, b.collision_sprites[1]) if len(b.collision_sprites) >= 2 else -1
        if idx1 < 0 or idx2 < 0:
            continue
        key = (min(idx1, idx2), max(idx1, idx2))
        if key not in grouped:
            grouped[key] = []
        grouped[key].append(b)

    if not grouped:
        lines.append("\t;; (no valid sprite pairs for collision checks)")
        return

    lines.append("\t;; Collision checks")
    lines.append("\tlda $d01e")
    lines.append("\tsta $d01e")
    lines.append("\ttax")

    for (i1, i2), behaviors in grouped.items():
        mask = (1 << i1) | (1 << i2)
        skip = _next_beh_label(cnt, "nocol")
        lines.append(f"\ttxa")
        lines.append(f"\tand #${mask:02X}")
        lines.append(f"\tbeq {skip}")
        for b in behaviors:
            lines.append(f"\tjsr beh_handler_{_safe_label(b.name)}")
        lines.append(f"{skip}:")
        lines.append("")
    lines.append("")


def _emit_collision_handlers(spec: "ProjectSpec", lines: list[str]) -> None:
    collision_behaviors = [b for b in spec.behaviors if b.type == "on_collision"]
    if not collision_behaviors:
        return

    for b in collision_behaviors:
        lines.append(f"beh_handler_{_safe_label(b.name)}:")
        cnt = _behavior_action_counter()
        for a in b.actions:
            _emit_action(spec, a, lines, cnt)
        lines.append("\trts")
        lines.append("")


def _emit_action(spec: "ProjectSpec", action: "Action", lines: list[str], cnt: list[int]) -> None:
    action_emitters = {
        "read_joystick": _emit_action_joystick,
        "update_sprite": _emit_action_update_sprite,
        "set_sprite_pos": _emit_action_set_sprite_pos,
        "inc_score": _emit_action_inc_score,
        "play_sound": _emit_action_play_sound,
        "check_collision": _emit_action_inline_collision,
        "display_text": _emit_action_display_text,
    }
    emitter = action_emitters.get(action.type)
    if emitter:
        emitter(spec, action, lines, cnt)
    else:
        lines.append(f"\t;; unknown action: {action.type}")


def _emit_action_joystick(spec: "ProjectSpec", action: "Action", lines: list[str], cnt: list[int]) -> None:
    port = action.params.get("port", "port2")
    if "2" in str(port):
        lines.append("\tlda $dc00")
        lines.append("\teor #$ff")
        lines.append("\tsta joystick_state")


def _emit_action_update_sprite(spec: "ProjectSpec", action: "Action", lines: list[str], cnt: list[int]) -> None:
    sprite_name = action.params.get("sprite", "")
    idx = _sprite_index_for(spec, sprite_name)
    if idx < 0:
        return

    ix_lo = 0xD000 + idx * 2
    ix_hi = 0xD001 + idx * 2

    directions = [
        ("JOY_UP", f"dec ${ix_hi:04X}", _next_beh_label(cnt, f"s{idx}u")),
        ("JOY_DOWN", f"inc ${ix_hi:04X}", _next_beh_label(cnt, f"s{idx}d")),
        ("JOY_LEFT", f"dec ${ix_lo:04X}", _next_beh_label(cnt, f"s{idx}l")),
        ("JOY_RIGHT", f"inc ${ix_lo:04X}", _next_beh_label(cnt, f"s{idx}r")),
    ]
    for joy_dir, op, skip in directions:
        lines.append(f"\t+c64_joy_check {joy_dir}, {skip}")
        lines.append(f"\t{op}")
        lines.append(f"{skip}:")


def _emit_action_set_sprite_pos(spec: "ProjectSpec", action: "Action", lines: list[str], cnt: list[int]) -> None:
    sprite_name = action.params.get("sprite", "")
    idx = _sprite_index_for(spec, sprite_name)
    if idx < 0:
        return

    x = action.params.get("x", 160)
    y = action.params.get("y", 120)
    ix_lo = 0xD000 + idx * 2
    ix_hi = 0xD001 + idx * 2

    if isinstance(x, str):
        x = _parse_int(x)
    if isinstance(y, str):
        y = _parse_int(y)

    lines.append(f"\tlda #<{x}")
    lines.append(f"\tsta ${ix_lo:04X}")
    lines.append(f"\tlda #<{y}")
    lines.append(f"\tsta ${ix_hi:04X}")

    if x > 255:
        lines.append(f"\tlda $d010")
        lines.append(f"\tora #${1 << idx:02X}")
        lines.append(f"\tsta $d010")
    else:
        lines.append(f"\tlda $d010")
        lines.append(f"\tand #${(~(1 << idx)) & 0xFF:02X}")
        lines.append(f"\tsta $d010")


def _emit_action_inc_score(spec: "ProjectSpec", action: "Action", lines: list[str], cnt: list[int]) -> None:
    amount = int(action.params.get("amount", 1))
    if amount >= 0:
        lines.append("\tclc")
        lines.append("\tlda score")
        lines.append(f"\tadc #<{amount}")
        lines.append("\tsta score")
        lines.append("\tlda score+1")
        lines.append(f"\tadc #>{amount}")
        lines.append("\tsta score+1")
    else:
        amt = abs(amount)
        lines.append("\tsec")
        lines.append("\tlda score")
        lines.append(f"\tsbc #<{amt}")
        lines.append("\tsta score")
        lines.append("\tlda score+1")
        lines.append(f"\tsbc #>{amt}")
        lines.append("\tsta score+1")


def _emit_action_play_sound(spec: "ProjectSpec", action: "Action", lines: list[str], cnt: list[int]) -> None:
    voice = int(action.params.get("voice", 1))
    note = str(action.params.get("note", ""))
    freq = int(action.params.get("frequency", 0))
    waveform = action.params.get("waveform", "triangle")
    duration = int(action.params.get("duration", 0))
    adsr = str(action.params.get("adsr", ""))
    volume = int(action.params.get("volume", 15))

    wf_map = {"triangle": 0x10, "saw": 0x20, "pulse": 0x40, "noise": 0x80}
    wf = wf_map.get(waveform.lower(), 0x10)

    adsr_map = {
        "organ": (0x04, 0x09), "piano": (0x00, 0x09),
        "pluck": (0x00, 0x01), "pad": (0x06, 0x0A),
        "bass": (0x01, 0x09),
    }
    base = 0xD400 + (voice - 1) * 7

    if note:
        sid_freq = note_to_sid_freq(note)
    elif freq:
        sid_freq = freq
    else:
        sid_freq = 1000

    lines.append(f"\t;; play_sound: voice {voice}, "
                 f"freq=${sid_freq:04X}" + (f" ({note})" if note else ""))

    lines.append(f"\tlda #<{sid_freq}")
    lines.append(f"\tsta ${base:04X}")
    lines.append(f"\tlda #>{sid_freq}")
    lines.append(f"\tsta ${base + 1:04X}")

    if adsr.lower() in adsr_map:
        atk, dec = adsr_map[adsr.lower()]
        lines.append(f"\t;; ADSR: {adsr}")
        lines.append(f"\tlda #${(atk << 4) | dec:02X}")
        lines.append(f"\tsta ${base + 5:04X}")
        lines.append(f"\tlda #${0xF0:02X}")
        lines.append(f"\tsta ${base + 6:04X}")

    lines.append(f"\tlda #${wf | 0x01:02X}")
    lines.append(f"\tsta ${base + 4:04X}")

    if duration > 0:
        lines.append(f"\tlda #{duration}")
        lines.append(f"\tsta sound_dur_{voice}")

    lines.append(f"\t+c64_sid_volume {volume}")


def _emit_action_inline_collision(spec: "ProjectSpec", action: "Action", lines: list[str], cnt: list[int]) -> None:
    sprites_raw = action.params.get("sprites", [])
    if isinstance(sprites_raw, str):
        sprites_raw = [s.strip() for s in sprites_raw.split(",")]
    if len(sprites_raw) < 2:
        return
    idx1 = _sprite_index_for(spec, sprites_raw[0])
    idx2 = _sprite_index_for(spec, sprites_raw[1])
    if idx1 < 0 or idx2 < 0:
        return
    mask = (1 << idx1) | (1 << idx2)
    skip = _next_beh_label(cnt, "col")
    lines.append(f"\tlda $d01e")
    lines.append(f"\tand #${mask:02X}")
    lines.append(f"\tbeq {skip}")
    lines.append(f"\tsta $d01e")
    lines.append(f"\tjsr beh_handler_{_safe_label(action.params.get('handler', sprites_raw[0] + '_' + sprites_raw[1]))}")
    lines.append(f"{skip}:")


def _emit_action_display_text(spec: "ProjectSpec", action: "Action", lines: list[str], cnt: list[int]) -> None:
    """Emit text display to screen RAM."""
    text = str(action.params.get("text", ""))
    if not text:
        return
    row = int(action.params.get("row", 0))
    col = int(action.params.get("col", 0))
    color = int(action.params.get("color", 0))

    screen_addr = spec.screen.screen_ram + row * 40 + col
    color_addr = 0xD800 + row * 40 + col
    label = _next_beh_label(cnt, "txt")
    lines.append(f"\t;; display_text: \"{text}\" at row {row}, col {col}")
    lines.append(f"\tldx #0")
    lines.append(f"{label}_lp:")
    lines.append(f"\tlda {label}_dat, x")
    lines.append(f"\tbeq {label}_dn")
    lines.append(f"\tsta ${screen_addr:04X}, x")
    if color:
        lines.append(f"\tlda #{color}")
        lines.append(f"\tsta ${color_addr:04X}, x")
    lines.append(f"\tinx")
    lines.append(f"\tbne {label}_lp")
    lines.append(f"{label}_dn:")
    lines.append("")
    lines.append(f"{label}_dat:")
    lines.append(f'\t!scr \"{text}\", 0')
    lines.append("")


def _emit_sprite_init_behavior(spec: "ProjectSpec", lines: list[str]) -> None:
    """Emit sprite init when behaviors exist."""
    if not spec.sprites:
        lines.append("init_sprites:")
        lines.append("\trts")
        lines.append("")
        return

    lines.append("init_sprites:")
    for s in spec.sprites:
        ix_lo = 0xD000 + s.index * 2
        ix_hi = 0xD001 + s.index * 2
        lines.append(f"\t;; Sprite {s.index}: {s.name}")
        lines.append(f"\tlda #<{s.x}")
        lines.append(f"\tsta ${ix_lo:04X}")
        lines.append(f"\tlda #<{s.y}")
        lines.append(f"\tsta ${ix_hi:04X}")
        lines.append(f"\tlda #${s.color:02X}")
        lines.append(f"\tsta ${0xD027 + s.index:04X}")
        if s.x > 255:
            lines.append(f"\tlda $d010")
            lines.append(f"\tora #${1 << s.index:02X}")
            lines.append(f"\tsta $d010")
    lines.append("\t+c64_sprite_enable_all")
    lines.append("\trts")
    lines.append("")


def _emit_behavior_update_sprites(spec: "ProjectSpec", lines: list[str]) -> None:
    """update_sprites is a no-op when behaviors exist — all sprite updates
    are handled in behaviors_update."""
    lines.append("update_sprites:")
    lines.append("\trts")
    lines.append("")


def _safe_label(name: str) -> str:
    return name.replace(" ", "_").replace("-", "_").lower()


# --- Backward-compatible sprite init (used when behaviors exist,  
# --- init_sprites is generated by _emit_sprite_init_behavior above) ---


def _emit_user_routines(spec: "ProjectSpec", lines: list[str]) -> None:
    lines.append("game_logic:")
    lines.append("\t;; User game logic — edit in routines/game_logic.acme")
    routines_dir = spec.project_dir / "routines"
    if (routines_dir / "game_logic.acme").exists():
        lines.append(f'\t!source "routines/game_logic.acme"')
    else:
        lines.append("\trts")
    lines.append("")

    for r in spec.routines:
        name = Path(r).stem
        if (routines_dir / f"{name}.acme").exists():
            lines.append(f"_{name}:")
            lines.append(f'\t!source "routines/{name}.acme"')
            lines.append("")


def _emit_sprite_data(spec: "ProjectSpec", lines: list[str]) -> None:
    if not spec.sprites:
        return
    lines.append("")
    lines.append(f"* = ${spec.memory.sprite_data:04X}")
    lines.append("")
    for s in spec.sprites:
        lines.append(f";; Sprite {s.index}: {s.name}")
        if s.data_file and (spec.project_dir / s.data_file).exists():
            lines.append(f'\t!bin "{s.data_file}"')
        else:
            lines.append(f"\t+c64_sprite_placeholder {s.index}")
    lines.append("")


def _emit_routines_footer(spec: "ProjectSpec", lines: list[str]) -> None:
    routines_dir = spec.project_dir / "routines"
    if not routines_dir.exists():
        return

    lines.append("")
    lines.append("\t;; -- User routines --")
    for acme_file in sorted(routines_dir.glob("*.acme")):
        name = acme_file.stem
        if name == "game_logic":
            continue
        if name not in spec.routines:
            lines.append(f'\t!source "routines/{acme_file.name}"')


def run_build(spec: "ProjectSpec") -> Path:
    src_dir = get_output_src_dir(spec.project_dir)
    build_dir = get_output_build_dir(spec.project_dir)
    src_dir.mkdir(parents=True, exist_ok=True)
    build_dir.mkdir(parents=True, exist_ok=True)

    asm_code = generate_assembly(spec)
    main_asm = src_dir / "main.acme"
    with open(main_asm, "w") as f:
        f.write(asm_code)

    routines_src = spec.project_dir / "routines"
    routines_dst = src_dir / "routines"
    if routines_src.exists():
        import shutil
        shutil.copytree(routines_src, routines_dst, dirs_exist_ok=True)

    assets_src = spec.project_dir / "assets"
    assets_dst = src_dir / "assets"
    if assets_src.exists():
        import shutil
        shutil.copytree(assets_src, assets_dst, dirs_exist_ok=True)

    return main_asm
